# permissions for end users to edit petclinicgoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: petclinicgo-editor-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - petclinicgoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - petclinicgoes/status
  verbs:
  - get
